# NeoAgent 配置文件
# @author: sun977
# @date: 2025.10.21
# @description: Agent端默认配置文件

# 应用配置
app:
  name: "neoagent"
  version: "1.0.0"
  environment: "development"
  debug: false

# 服务器配置 Master 端口 8123 Agent 端口 8321
server:
  host: "0.0.0.0"
  port: 8321
  api_version: "v1"
  prefix: "/api"
  debug: false
  enable_middleware: true
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60
  max_header_bytes: 1048576  # 1MB
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""

# 日志配置
log:
  level: "info"
  format: "json"
  output: "file"
  file_path: "logs/agent.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true
  caller: true

# 数据库配置
database:
  type: "sqlite"
  host: "localhost"
  port: 3306
  username: ""
  password: ""
  database: "data/agent.db"
  dsn: "data/agent.db"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"
  conn_max_idle_time: "30m"
  log_level: "warn"
  slow_threshold: "200ms"

# Master连接配置
master:
  address: "localhost"
  port: 8080
  protocol: "http"
  connect_timeout: "10s"
  request_timeout: "30s"
  heartbeat_interval: "30s"
  reconnect_interval: "5s"
  max_reconnect_attempts: 10
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""
    skip_verify: false

# Agent配置
agent:
  id: "neoagent-001"  # Agent唯一标识
  name: "neoagent"
  version: "1.0.0"
  type: "scanner"
  work_dir: "./work"
  temp_dir: "./temp"
  log_dir: "./logs"
  data_dir: "./data"
  max_concurrent_tasks: 10
  task_timeout: "30m"
  resources:
    cpu_limit: 80
    memory_limit: 1024
    disk_limit: 10240

# 中间件配置
middleware:
  # 认证中间件
  auth:
    auth_method: "none"
    api_key: ""
    api_key_header: "X-API-Key"
    jwt_secret: ""
    whitelist_ips: []
    skip_paths:
      - "/api/v1/health"
      - "/api/v1/metrics"

  # 日志中间件
  logging:
    enable_request_log: true
    enable_response_log: true
    log_request_body: false
    log_response_body: false
    slow_request_threshold: "1s"
    skip_paths:
      - "/api/v1/health"
      - "/api/v1/metrics"
    max_request_body_size: 1024
    max_response_body_size: 1024

  # CORS中间件
  cors:
    enabled: true
    allow_all_origins: true
    allow_origins: []
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
      - "X-Requested-With"
    expose_headers: []
    allow_credentials: false
    max_age: "12h"

  # 限流中间件
  rate_limit:
    enabled: false
    requests_per_second: 100
    burst_size: 200
    strategy: "token_bucket"
    window_size: "1m"
    status_code: 429
    message: "Rate limit exceeded"
    skip_paths:
      - "/api/v1/health"
      - "/api/v1/metrics"
    skip_ips: []

# 执行器配置
executor:
  types:
    - "system"
    - "nmap"
    - "nuclei"
    - "masscan"
  default: "system"

# 监控配置
monitor:
  interval: "30s"
  retention_period: "24h"
  alerts:
    - name: "disk_space_low"
      metric: "disk_usage"
      condition: ">"
      threshold: 85.0
      duration: "1m"
      severity: "warning"
      message: "Disk space is low"

# 安全配置
security:
  api_key: ""  # 从环境变量 AGENT_API_KEY 获取
  jwt_secret: ""  # 从环境变量 JWT_SECRET 获取
  jwt_expiration: "24h"
  encryption_key: ""  # 从环境变量 ENCRYPTION_KEY 获取
  ip_whitelist: []
  enable_ip_whitelist: false

# ---------- 其他配置 ----------
# 插件模块配置
plugins:
  enabled: true
  path: "./plugins"
  auto_load: true
  max_concurrent: 5

# Scan模块配置(需要包含各个扫描子模块的配置，如资产扫描、漏洞扫描、端口扫描等)
scan:
  enabled: true
  asset_scan:
    enabled: true
    interval: "12h"
    targets: []
  vulnerability_scan:
    enabled: true
    interval: "24h"
    targets: []
  port_scan:
    enabled: true
    interval: "4h"
    targets: []

